spring.application.name=autocomplete
server.port=8080

spring.data.redis.host=redis
spring.data.redis.port=6379

# Optionally, to run locally without docker-compose, change host to localhost 
# and override via environment variable when dockerized
